In [1]:
from ls.metrics import compute_classification_metrics

In [2]:
import numpy as np
from sklearn.metrics import roc_auc_score
from pprint import pprint

# Assume 4 classes (e.g., ICBHI: 0=normal, 1=crackle, 2=wheeze, 3=both)
n_classes = 4
y_true = np.random.randint(0, n_classes, size=200)
y_pred = np.random.randint(0, n_classes, size=200)

# simulate model probabilities (softmax outputs)
y_prob = np.random.rand(200, n_classes)
y_prob = y_prob / y_prob.sum(axis=1, keepdims=True)

metrics = compute_classification_metrics(y_true, y_pred, y_prob, n_classes)
pprint(metrics)

[[11 18 19 13]
 [16 15 12  6]
 [11 10 11 16]
 [ 6 17 12  7]]
{'accuracy': np.float64(22.0),
 'auroc_macro': np.float64(49.81687463885007),
 'auroc_weighted': np.float64(49.722859183257974),
 'balanced_acc': np.float64(22.057091279134603),
 'f1_macro': np.float64(21.677652712461132),
 'f1_weighted': np.float64(21.810066044766533),
 'icbhi_score': 20.88689703972193,
 'sensitivity': 23.741007194227524,
 'specificity': 18.03278688521634}


In [3]:
n_classes = 4
# Only classes 0 and 1 appear in y_true
y_true = np.random.randint(0, 2, size=200)
y_pred = np.random.randint(0, 2, size=200)
y_prob = np.random.rand(200, n_classes)
y_prob = y_prob / y_prob.sum(axis=1, keepdims=True)

metrics = compute_classification_metrics(y_true, y_pred, y_prob, n_classes)
pprint(metrics)

[[55 51  0  0]
 [43 51  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
{'accuracy': np.float64(53.0),
 'auroc_macro': -1,
 'auroc_weighted': -1,
 'balanced_acc': np.float64(53.07105580088318),
 'f1_macro': np.float64(52.9811924769908),
 'f1_weighted': np.float64(53.0376150460184),
 'icbhi_score': 53.071055800829846,
 'sensitivity': 54.255319148878456,
 'specificity': 51.886792452781236}
